"""Add custom_instructions to transformation requests

Revision ID: 513aecbe2c4c
Revises: ae0421b2b183
Create Date: 2026-09-04 23:13:34.007893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '513aecbe2c4c'
down_revision: Union[str, Sequence[str], None] = 'ae0421b2b183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transformation_requests', sa.Column('custom_instructions', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transformation_requests', 'custom_instructions')
    # ### end Alembic commands ###
