"""Add template_configs and enums

Revision ID: e024682296ae
Revises: 513aecbe2c4c
Create Date: 2026-09-05 10:44:07.725658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e024682296ae'
down_revision: Union[str, Sequence[str], None] = '513aecbe2c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create ENUM types explicitly in postgresql
    artifact_status = postgresql.ENUM('GENERATING', 'GENERATED', 'VERIFYING', 'PASSED', 'REVISION_REQUIRED', 'FAILED', 'FINALIZED', name='artifactstatus')
    artifact_status.create(op.get_bind())
    
    transformation_status = postgresql.ENUM('QUEUED', 'PLANNING', 'GENERATING', 'VERIFYING', 'RENDERING', 'COMPLETED', 'FAILED', name='transformationstatus')
    transformation_status.create(op.get_bind())
    
    verification_status = postgresql.ENUM('PENDING', 'PASSED', 'REVISION_REQUIRED', 'FAILED', name='verificationstatus')
    verification_status.create(op.get_bind())

    # Data migrations to clean up old string statuses
    op.execute("UPDATE artifacts SET status = 'PASSED' WHERE status = 'verified'")
    op.execute("UPDATE artifacts SET status = 'GENERATING' WHERE status = 'generating'")
    op.execute("UPDATE transformation_requests SET status = 'PLANNING' WHERE status = 'PROCESSING'")
    op.execute("UPDATE transformation_requests SET status = 'PLANNING' WHERE status = 'processing'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artifacts', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=artifact_status,
               existing_nullable=False,
               postgresql_using='status::text::artifactstatus')
    op.add_column('transformation_requests', sa.Column('template_configs', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('transformation_requests', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=transformation_status,
               existing_nullable=False,
               postgresql_using='status::text::transformationstatus')
    op.alter_column('verification_results', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=verification_status,
               existing_nullable=False,
               postgresql_using='status::text::verificationstatus')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verification_results', 'status',
               existing_type=sa.Enum('PENDING', 'PASSED', 'REVISION_REQUIRED', 'FAILED', name='verificationstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('transformation_requests', 'status',
               existing_type=sa.Enum('QUEUED', 'PLANNING', 'GENERATING', 'VERIFYING', 'RENDERING', 'COMPLETED', 'FAILED', name='transformationstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('transformation_requests', 'template_configs')
    op.alter_column('artifacts', 'status',
               existing_type=sa.Enum('GENERATING', 'GENERATED', 'VERIFYING', 'PASSED', 'REVISION_REQUIRED', 'FAILED', 'FINALIZED', name='artifactstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
